# Generated by Django 5.2.1 on 2025-08-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adventures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='create_tour_package',
            options={'verbose_name': 'Tour package', 'verbose_name_plural': 'Tour packages for Approval'},
        ),
        migrations.AlterField(
            model_name='create_tour_package',
            name='place_image',
            field=models.ImageField(upload_to='tour_packages/'),
        ),
    ]
