# Generated by Django 5.2.1 on 2025-08-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adventures', '0002_alter_create_tour_package_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage_bills',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='manage_bills',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
    ]
