# Generated by Django 5.2.1 on 2025-08-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adventures', '0003_manage_bills_amount_paid_manage_bills_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage_bills',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
